### ISSUE TITLE
Type mismatch with roslyn runtime compilation.

### ISSUE THREAD

**Issue by malylemire1** [simpleinjector/SimpleInjector#121]
###### I randomly get this error when using simple injector with types from a roslyn compiled assembly in a visual studio package : ######

```
[A]SimpleInjector.Lifestyles.ScopedRegistration`2[MMBS.CodeGen.GenerateClientRepos,MMBS.CodeGen.GenerateClientRepos]
   cannot be cast to
[B]SimpleInjector.Lifestyles.ScopedRegistration`2[MMBS.CodeGen.GenerateClientRepos,MMBS.CodeGen.GenerateClientRepos].
Type A originates from 'SimpleInjector, Version=3.0.3.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' in the context 'LoadFrom' at location 'C:\Users\mlemire\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\hud5j4kh.i05\SimpleInjector.dll'.
Type B originates from 'SimpleInjector, Version=3.0.3.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' in the context 'LoadFrom' at location 'C:\Users\mlemire\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\hud5j4kh.i05\SimpleInjector.dll'.
Details :    at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Internals.ContainerControlledCollection`1.<GetEnumerator>d__24.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at MMBS.Core.CodeGen.MMBSCodeGenApp.<AnalyzeSolution>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MMBS.Core.CodeGen.MMBSCodeGenApp.<Generate>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MMBS.CodeGen.Pkg.GenerateAll.<MenuItemCallback>d__15.MoveNext() in C:\Users\mlemire\Desktop\Tourmed\MMBS\MMBS.CodeGen.Pkg\Commands\GenerateAll.cs:line 113
```

###### This is the registration code : ######

```csharp
public void RegisterAllForScope(Type serviceType, IEnumerable<Type> assemblyTypes)
{
    IEnumerable<Type> types = assemblyTypes
        .Where(t => serviceType.IsAssignableFrom(t));
    IList<Registration> registrations = new List<Registration>();
    foreach (Type type in types)
    {
        registrations.Add(executionScope.CreateRegistration(type, this));
    }
    RegisterCollection(serviceType, registrations);
}

private static void Register(DependencyInjector dependencyInjector, IEnumerable<Type> assemblyTypes)
{
    //Register code generation projects
    dependencyInjector.RegisterAllForScope(typeof(ICodeAnalysisProject), assemblyTypes);
    dependencyInjector.RegisterAllForScope(typeof(ICodeModificationProject), assemblyTypes);
    dependencyInjector.RegisterAllForScope(typeof(ICodeGenerationProject), assemblyTypes);
}
```

###### This is the code to compile the assembly : ######
```csharp
public static async Task<Assembly> GetCodeGenerationAssembly(VisualStudioWorkspace workspace, string codeGenAssemblyName)
{
    Project codeGenProject = workspace.CurrentSolution.Projects.Where(x => x.Name == codeGenAssemblyName).FirstOrDefault();
    if (codeGenProject != null)
    {
        Compilation compilation = await codeGenProject.GetCompilationAsync();
        if (compilation != null)
        {
            using (MemoryStream dllStream = new MemoryStream())
#if DEBUG
            using (MemoryStream pdbStream = new MemoryStream())
#endif
            {
#if DEBUG
                EmitResult result = compilation.Emit(dllStream, pdbStream);
#else
                EmitResult result = compilation.Emit(dllStream);
#endif
                if (!result.Success)
                {
                    IEnumerable<Diagnostic> failures = result.Diagnostics.Where(diagnostic =>
                        diagnostic.IsWarningAsError ||
                        diagnostic.Severity == DiagnosticSeverity.Error);
                    string failuresException = "Failed to compile code generation project : \r\n";
                    foreach (Diagnostic diagnostic in failures)
                    {
                        failuresException += $"{diagnostic.Id} : {diagnostic.GetMessage()}\r\n";
                    }
                    throw new Exception(failuresException);
                }
                else
                {
                    dllStream.Seek(0, SeekOrigin.Begin);
#if DEBUG
                    return Assembly.Load(dllStream.ToArray(), pdbStream.ToArray());
#else
                    return Assembly.Load(dllStream.ToArray());
#endif
                }
            }
        }
    }
    return null;
}
```

###### This is the instance retrieval code : ######
```csharp
public IDisposable BeginScope()
{
    return this.BeginExecutionContextScope();
}

public static async Task Generate(VisualStudioWorkspace workspace, string codeGenAssemblyName)
{
    Assembly codeGenAssembly = await GetCodeGenerationAssembly(workspace, codeGenAssemblyName);
    if (codeGenAssembly != null)
    {
        Configure(codeGenAssembly.GetTypes());
        using (DI.BeginScope())
        {
            IEnumerable<ICodeGenerationProject> codeGenProjects = DI.GetAllInstances<ICodeGenerationProject>();
            IEnumerable<ICodeModificationProject> codeModifProjects = DI.GetAllInstances<ICodeModificationProject>();
            IEnumerable<ICodeAnalysisProject> codeAnalyzeProjects = DI.GetAllInstances<ICodeAnalysisProject>();
            Solution solution = workspace.CurrentSolution;
            await AnalyzeSolution(solution, codeGenProjects, codeAnalyzeProjects);
            solution = await ModifySolution(solution, codeGenProjects, codeModifProjects);
            if (!workspace.TryApplyChanges(solution))
            {
                throw new InvalidOperationException("Cannot apply changes to current solution. The workspace may have changed since it was loaded.");
            }
        }
    }
    else
    {
        throw new FileNotFoundException("The project " + codeGenAssemblyName + " must be loaded in current solution.");
    }
}
```

**Comment by dotnetjunkie** [comment]
This problem seems unrelated to Simple Injector. You might want to post this at the Roslyn forum instead.
