### ISSUE TITLE
DuplicateKeyException when using AspNetRequestScoping in aspnet core 1.1 RTM

### ISSUE THREAD

**Issue by rangp** [simpleinjector/SimpleInjector#342]
After updating to aspnet core 1.1 RTM I'm getting duplicate key exceptions when using AspNetRequestScoping via the `SimpleInjector.Integration.AspNetCore.Mvc` package. The setup has been working fine with aspnet core 1.0 before.  Any ideas why this can happen or any plans to support aspnet core 1.1? I read that some changes to the DI abstraction have been made in order to improve integration with third-party containers. (see https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/)

I temporarily disabled request scoping and switched to transient lifestyles instead. This fixed the error, so it seems to be restricted to the request scoping part.

Here are the exception details:

Message:
```
An item with the same key has already been added. Key: System.Object
```

Method:
```
SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.<>c__DisplayClass0_0.<<UseSimpleInjectorAspNetRequestScoping>b__0>d.MoveNext()
```

Callstack
```
System.ArgumentException:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Http.Internal.ItemsDictionary.System.Collections.Generic.IDictionary<System.Object,System.Object>.Add(Object key, Object value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter.OnResultExecuted(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.<>c__DisplayClass0_0.<<UseSimpleInjectorAspNetRequestScoping>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EnBW.Foundation.Web.IpRestrictionMiddleware.<Invoke>d__6.MoveNext() (C:\a\1\s\_Foundation\EnBW.Foundation.Web.Core\IpRestrictionMiddleware.cs: 58)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
```

**Comment by dotnetjunkie** [comment]
Can you post some code that allows me to reproduce the issue?

Do note that aĺ the changes made to the DI system should not affect Simple Injector, because these changes are focused around the Conforming Container which Simple Injector does not use. I'm dazzled that there seems to be a breaking change in v1.1 that affects Simple Injector.

**Comment by rangp** [comment]
So I was making an effort to reproduce the error, but it proved to be specific to microsoft azure, since I'm hosting the site as an azure web app. Turns out there was an old .dll on the server, that was loaded along with the new version and somehow messed up the request pipeline. I don't know exactly how this lead to a duplicate key exception, but it wasn't a simple injector issue after all. Sorry to bother you with it.
