### ISSUE TITLE
Question - Verify Fails in Asp.Net Core Startup - Creating the instance for type AccountController failed. No HttpContext

### ISSUE THREAD

**Issue by simonscoffins** [simpleinjector/SimpleInjector#403]
Pretty sure this is down to a registration/wiring problem on my part:

The application works fine but the SimpleInjector Verify throws a "No HttpContext Error" in the controller.

I implemented simple adapter classes for cross wiring a couple of the Identity manager utilities to decouple my app from the framework - see my configuration below:

Should the verify call be placed else where or is it the way I've cross-wired the framework classes?

Thanks for any advice.

**Startup class:**

``` c#
public void ConfigureServices(IServiceCollection services) {

    // Add framework services.
    services.AddDbContext<AppDbContext>(options => options.UseSqlServer(_configurationRoot.GetConnectionString("DefaultConnection")));

    services.AddIdentity<User, Role>(options => {})
        .AddEntityFrameworkStores<AppDbContext, int>()
        .AddDefaultTokenProviders();

    services.AddMvc();

    // register simple injector
    services.AddSingleton<IControllerActivator>(new SimpleInjectorControllerActivator(_container));
    services.AddSingleton<IViewComponentActivator>(new SimpleInjectorViewComponentActivator(_container));
    services.UseSimpleInjectorAspNetRequestScoping(_container);
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) {

    loggerFactory.AddConsole();

    app.UseDeveloperExceptionPage();
    app.UseStatusCodePages();
    app.UseStaticFiles();
    // useIdentity must go before useMvc
    app.UseIdentity();
    app.UseMvcWithDefaultRoute();

    // app composition root with simple injector
    InitializeContainer(app);
    _container.Verify();
}
    
private void InitializeContainer(IApplicationBuilder app) {

    _container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

    // Add application presentation components:
    _container.RegisterMvcControllers(app);
    _container.RegisterMvcViewComponents(app);
                
    _container.Register<IUnitOfWork>(app.GetRequestService<AppDbContext>, Lifestyle.Scoped);
    _container.Register<IGetPeopleService, GetPeopleService>(Lifestyle.Scoped);

    RegisterCrosWireServices(app);
}
    
private void RegisterCrosWireServices(IApplicationBuilder app) {

    _container.Register(app.GetRequestService<UserManager<User>>);
    _container.Register(app.GetRequestService<SignInManager<User>>);

    // register cross wire adapters
    _container.Register<IUserManager, UserManagerAdapter>(Lifestyle.Scoped);
    _container.Register<ISignInManager, SignInManagerAdapter>(Lifestyle.Scoped);
}
```
**Adapter interface and class for UserManger:**    
``` c#
public interface IUserManager {
    Task<User> FindByNameAsync(string userName);
    Task<IdentityResult> CreateAsync(User user, string password);
}

public sealed class UserManagerAdapter : IUserManager {

    private readonly UserManager<User> _userManager;

    public UserManagerAdapter(UserManager<User> userManager) {
        _userManager = userManager;
    }

    public async Task<User> FindByNameAsync(string userName) {
        return await _userManager.FindByNameAsync(userName);
    }

    public async Task<IdentityResult> CreateAsync(User user, string password) {
        return await _userManager.CreateAsync(user, password);
    }
}
```
**AccountController constructor:**

``` c#
[Authorize]
public class AccountController : Controller {

    private readonly IUserManager _userManager;

    public AccountController(IUserManager userManager) {

    _userManager = userManager;
}
```

**Comment by dotnetjunkie** [comment]
Can you post the exact exception message and other details like stack trace (of the inner exceptions as well)?

**Comment by simonscoffins** [comment]
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=The configuration is invalid. Creating the instance for type AccountController failed. No HttpContext. Please make sure this method is called within the context of an active HTTP request.
  Source=SimpleInjector
  StackTrace:
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at Web.Empty.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\xxx\Documents\Visual Studio 2017\Projects\CorePoc\Web.Empty\Startup.cs:line 87

Inner Exception 1:
ActivationException: No HttpContext. Please make sure this method is called within the context of an active HTTP request.

Inner Exception 2:
InvalidOperationException: No HttpContext. Please make sure this method is called within the context of an active HTTP request.

```

**Comment by simonscoffins** [comment]
Hope that helps

**Comment by dotnetjunkie** [comment]
Can you post the _stack traces_ of those inner exceptions as well?

**Comment by simonscoffins** [comment]
Sorry about that

```
InnerExceptiion 1:

StackTrace:

at SimpleInjector.InstanceProducer.GetInstance()
at SimpleInjector.InstanceProducer.VerifyInstanceCreation()


InnerException 2:

StackTrace: 

at SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.GetRequestServiceProvider(IApplicationBuilder builder)
at SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.GetRequestService[T](IApplicationBuilder builder)
at lambda_method(Closure )
at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
at lambda_method(Closure )
at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
at SimpleInjector.InstanceProducer.GetInstance()

```

**Comment by dotnetjunkie** [comment]
Ha, now I see. You are making the following registrations:

``` c#
_container.Register(app.GetRequestService<UserManager<User>>);
_container.Register(app.GetRequestService<SignInManager<User>>);
```

This is equivalent to doing the following:

``` c#
_container.Register(() => app.GetRequestService<UserManager<User>>());
```

In other words, you register a delegate as instance creator for a transient instance. Simple Injector will call such delegate to try creating such instance once you call `Verify()`. Since at the time you call `Verify()` there is no active HTTP request, its impossible to create request scoped services from ASP.NET and that's why this fails.

Because of that, the [Simple Injector Integration Guidelines for ASP.NET Core](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) use the following example:

``` c#
container.RegisterSingleton<Func<IViewBufferScope>>(app.GetRequestService<IViewBufferScope>);
```

Or converted you your case:

``` c#
_container.RegisterSingleton<Func<UserManager<User>>>(app.GetRequestService<UserManager<User>>);
_container.RegisterSingleton<Func<SignInManager<User>>>(app.GetRequestService<SignInManager<User>>);
```

What happens here is that we don't register `UserManager<User>` but instead `Func<UserManager<User>>` as service. Since we now supply a single instance of the service (the delegate) instead of passing in an `instance creator`, Simple Injector doesn't try to call that delegate.

By doing this, you can now let your code depend on `Func<UserManager<User>>` and let that dependency be resolved at runtime when you call it. ASP.NET Core will in that case manage its lifestyle, not Simple Injector.

**Comment by simonscoffins** [comment]
Ah, I think the penny is dropping and starting to understand the idea. Thanks for looking at this. I re-read your docs and and blog: https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/

So my adapter will depend on Fun<TService> like so:

```
    public interface IUserManager {
        Task<User> FindByNameAsync(string userName);
        Task<IdentityResult> CreateAsync(User user, string password);
    }

    public sealed class UserManagerAdapter : IUserManager {

        private readonly Func<UserManager<User>> _userManager;

        public UserManagerAdapter(Func<UserManager<User>> userManager ) {
            _userManager = userManager;
        }

        public async Task<User> FindByNameAsync(string userName) {
            return await _userManager.Invoke().FindByNameAsync(userName);
        }

        public async Task<IdentityResult> CreateAsync(User user, string password) {
            return await _userManager.Invoke().CreateAsync(user, password);
        }
    }

```
Still struggling with implementation though: 

The registration: 
`            _container.RegisterSingleton<Func<UserManager<User>>>(app.GetRequestService<UserManager<User>>);
`
is throwing a compile error:

`Error	CS0121	The call is ambiguous between the following methods or properties: 'Container.RegisterSingleton<TService>(TService)' and 'Container.RegisterSingleton<TService>(Func<TService>)'
`

Tried a couple of different variations but no joy.

**Comment by dotnetjunkie** [comment]
UserManagerAdapter : IUserManager {

        private readonly Func<UserManager<User>> _userManager;


Ah yes, that gets the C# compiler confused. Sorry about that.

Instead of registering the factory though, try this:

``` c#
container.RegisterSingleton<IUserManager>(
    new UserManagerAdapter(
        app.GetRequestService <UserManager<User>>));
```

**Comment by simonscoffins** [comment]
Brilliant, that got it.

Thanks so much for taking the time.
