### ISSUE TITLE
Entity Framework Core Multiple DbContext CrossWiring failing

### ISSUE THREAD

**Issue by Jonatthu** [simpleinjector/SimpleInjector#494]
So I have 2 DbContext like this...
```
    public class AccountsDbContext : DbContext
    {

        public AccountsDbContext(DbContextOptions<AccountsDbContext> options)
            : base(options)
        {
        }
   }
```
And...
```
    public class AccountsLanguageDbContext : DbContext
    {

        public AccountsLanguageDbContext(DbContextOptions<AccountsLanguageDbContext> options)
            : base(options)
        {
        }
   }
```

And configure them like this with simple injector:

With normal DI from asp core
```
            services.AddDbContextPool<AccountsDbContext>(
                optionsAction => optionsAction.UseSqlServer(Configuration["ConnectionString"])
            );

            services.AddDbContextPool<AccountsLanguageDbContext>(
                options => options.UseSqlServer(Configuration["ConnectionString1"])
            );
```
then with simple injector

```
            container.CrossWire<AccountsDbContext>(app);
            container.CrossWire<AccountsLanguageDbContext>(app);
```

And the error message is:

```
Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0]
```

How can I configure simple injector to CrossWire this correctly?

**Comment by dotnetjunkie** [comment]
That doesn't seem like an error comming from Simple Injector. Please post the full exception details, i.e. stack trace, message an exception type name of the exception and all its inner exceptions.

**Comment by Jonatthu** [comment]
```
PM> Add-Migration Initial -Context AccountsDbContext
Application startup exception: System.InvalidOperationException: The configuration is invalid. Creating the instance for type GraphQLController failed. Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0] ---> SimpleInjector.ActivationException: Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0] ---> System.ArgumentException: Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0]
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, Expression[] arguments)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.CreateActivator(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1..ctor(DbContextOptions options)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__2`1.<AddDbContextPool>b__2_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method(Closure )
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at Accounts.Api.Middleware.DependencyInjection.<>c__DisplayClass2_0.<InitializeSimpleInjectorContainer>b__11(Type type) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 124
   at Accounts.Api.GraphQL.AccountsGraphSchema..ctor(Func`2 resolveType) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\GraphQL\AccountsGraphSchema.cs:line 14
   at Accounts.Api.Middleware.DependencyInjection.<>c__DisplayClass2_0.<InitializeSimpleInjectorContainer>b__10() in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 124
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at Accounts.Api.Middleware.DependencyInjection.InitializeSimpleInjectorContainer(IApplicationBuilder app, Container container) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 132
   at Accounts.Api.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory, IPermissionsFactory permissionService) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Startup.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.InjectApiVersionRoutePolicy.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: The configuration is invalid. Creating the instance for type GraphQLController failed. Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0] ---> SimpleInjector.ActivationException: Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0] ---> System.ArgumentException: Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0]
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, Expression[] arguments)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.CreateActivator(DbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1..ctor(DbContextOptions options)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__2`1.<AddDbContextPool>b__2_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method(Closure )
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at Accounts.Api.Middleware.DependencyInjection.<>c__DisplayClass2_0.<InitializeSimpleInjectorContainer>b__11(Type type) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 124
   at Accounts.Api.GraphQL.AccountsGraphSchema..ctor(Func`2 resolveType) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\GraphQL\AccountsGraphSchema.cs:line 14
   at Accounts.Api.Middleware.DependencyInjection.<>c__DisplayClass2_0.<InitializeSimpleInjectorContainer>b__10() in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 124
   at lambda_method(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Scope.GetInstanceInternal[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at Accounts.Api.Middleware.DependencyInjection.InitializeSimpleInjectorContainer(IApplicationBuilder app, Container container) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Middleware\DependencyInjection.cs:line 132
   at Accounts.Api.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory, IPermissionsFactory permissionService) in C:\Users\JNungaray\Source\Repos\Accounts\Jonatthu.Accounts\Accounts.Api\Startup.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.InjectApiVersionRoutePolicy.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: The configuration is invalid. Creating the instance for type GraphQLController failed. Expression of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsLanguageDbContext]' cannot be used for constructor parameter of type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Accounts.Data.AccountsDbContext]'
Parameter name: arguments[0]
Unable to create an object of type 'AccountsDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<AccountsDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

**Comment by dotnetjunkie** [comment]
As the exception clearly shows, the problem originates from Microsoft.EntityFrameworkCore.Internal.DbContextPool`1, not from Simple Injector.

I'm afraid I don't know why DbContextPool is throwing this exception. As more often is the case, exceptions thrown by .NET code can be cryptic or deceptive.

Does Contect pooling even support multiple DbContext types?

**Comment by Jonatthu** [comment]
@dotnetjunkie probably is related to this https://github.com/aspnet/EntityFrameworkCore/issues/9433

**Comment by dotnetjunkie** [comment]
Yep, that seems like it is. Your configuration is clearly not supported.

**Comment by Jonatthu** [comment]
Just for other people @dotnetjunkie 

Use this config until EF Core 2.1 comes :) 


```
            services.AddDbContext<AccountsDbContext>(
                optionsAction => optionsAction.UseSqlServer(Configuration["ConnectionString"])
            );

            services.AddDbContext<AccountsLanguageDbContext>(
                options => options.UseSqlServer(Configuration["ConnectionString1"])
            );
```
With this works!

**Comment by ricklambrechts** [comment]
@Jonatthu Thank you for supplying this workaround!
