### ISSUE TITLE
Simple Injector and PrecompiledViews?

### ISSUE THREAD

**Issue by deckerbl** [simpleinjector/SimpleInjector#527]
I seem to be getting an error when using simple injector with .Net Core 2.0 and publishing.  The application works fine from my desktop but if I publish I get a "Cannot load or find precompiledviews.dll" error.  The library does exist in the deployment.  When I remove the simple injector initialization logic the error goes away.  Has anyone seen this problem.  This is using Asp.net core 2.0.5 and simple injector 4.1

**Comment by deckerbl** [comment]
Looks like this is more of an issue with Activator.CreateInstance, which the RegisterPackages uses along with the IPackage interface.  For some reason this is not working in .Net Core 2.

**Comment by dotnetjunkie** [comment]
Can you provide full exception details withstack traces?

**Comment by deckerbl** [comment]
Here is the code and the stack trace.

 var path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var assemblies =
                from file in new DirectoryInfo(path).GetFiles()
                where file.Name.Contains("Doit.Esas") && file.Extension.Contains(".dll")
                select Assembly.Load(AssemblyName.GetAssemblyName(file.FullName));

            _container.RegisterPackages(assemblies);


   [ExcludeFromCodeCoverage]
    public class Bootstrapper: IPackage
    {
        public void RegisterServices(Container container)
        {
            container.Register<IGetUserAccountQuery, GetUserAccountQuery>(Lifestyle.Scoped);
            container.Register<IGetLogQuery, GetLogQuery>(Lifestyle.Scoped);
            container.Register<IGetLogDetailQuery, GetLogDetailQuery>(Lifestyle.Scoped);
            container.Register<ICommandHandler<CreateUserAccountCommand>, CreateUserAccountCommandHandler>(Lifestyle.Scoped);
            container.Register<IUserAccountFactory, UserAccountFactory>(Lifestyle.Scoped);
        }


System.IO.FileNotFoundException: Could not load file or assembly 'Doit.Esas.Web.Identity2.PrecompiledViews, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Doit.Esas.Web.Identity2.PrecompiledViews, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Doit.Esas.Web.Identity2.Startup.<>c.<InitializeContainer>b__10_1(FileInfo file) in C:\source\Workspaces\DoIT-ESAS\Branches\Dev\Doit.Esas.Web.Identity2\Startup.cs:line 141
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SimpleInjector.PackageExtensions.GetPackagesToRegister(Container container, IEnumerable`1 assemblies)
   at SimpleInjector.PackageExtensions.RegisterPackages(Container container, IEnumerable`1 assemblies)
   at Doit.Esas.Web.Identity2.Startup.InitializeContainer(IApplicationBuilder app) in C:\source\Workspaces\DoIT-ESAS\Branches\Dev\Doit.Esas.Web.Identity2\Startup.cs:line 143
   at Doit.Esas.Web.Identity2.Startup.Configure(IApplicationBuilder app) in C:\source\Workspaces\DoIT-ESAS\Branches\Dev\Doit.Esas.Web.Identity2\Startup.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by dotnetjunkie** [comment]
The stack trace shows your call to `Assembly.Load` (Startup.cs, line 141) fails when loading `Doit.Esas.Web.Identity2.PrecompiledViews`.

This has nothing to do with Simple Injector. You'll find that this call will as well fail without Simple Injector's involvement. If you call `assemblies.ToArray()`, you'll find that the call to `.ToArray()` will fail with that exact exception. For instance, change the call to `RegisterPackages` to:

``` c#
_container.RegisterPackages(assemblies.ToArray());
```

If you inspect the new stack trace after running the application with this adjustment, you'll see that there are no Simple Injector calls within the call stack. The problem lies somewhere else.

_Why_ that call is failing is unclear to me. I tried to reproduce the issue locally, but it seems to be working fine. This might be a .NET Core thing, but I'm not sure.

**Comment by deckerbl** [comment]
Thanks for taking a look.  I think it's a .net core thing as well.  I was able to reproduce without simple injector.  Its the call to Activator.CreateInstance that fails when the code has been published.  I will probably push a sample to my MS contact.

By the way. I love simple injector!  The verify functionality has saved me many headaches!

**Comment by dotnetjunkie** [comment]
You're welcome.
