### ISSUE TITLE
ASP.NET Core Controllers defaulted to Transient, which should be scoped instead

### ISSUE THREAD

**Issue by rexcfnghk** [simpleinjector/SimpleInjector#795]
## Describe the bug
Simple Injector is throwing a `DiagnosticVerificationException` telling me a controller has been registered as transient, but implements `IDisposable` when the application starts up.

## Expected behavior
No exception thrown because `TestController` should be registered as scoped.

## Actual behavior
An `DiagnosticVerificationException` is thrown.

```
SimpleInjector.DiagnosticVerificationException: The configuration is invalid. The following diagnostic warnings were reported:
-[Disposable Transient Component] TestController is registered as transient, but implements IDisposable.
See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.
   at SimpleInjector.Container.ThrowOnDiagnosticWarnings()
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at WebApplication.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\rex\source\WebApplication\WebApplication\Startup.cs:line 59
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

## To Reproduce
I followed the documentation and installed Simple Injector in my ASP.NET Core 3.1 project:

```c#
public sealed class Startup
{
    private readonly Container _container = new Container();

    public Startup(IConfiguration configuration)
    {
        _container.Options.ResolveUnregisteredConcreteTypes = false;
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services 
    // to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();

        services.AddSimpleInjector(
            _container,
            options => options.AddAspNetCore().AddControllerActivation());

        InitializeContainer(_container);
    }

    // This method gets called by the runtime. Use this method to configure
    // the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseSimpleInjector(_container);

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseHttpsRedirection();

        app.UseRouting();

        app.UseAuthorization();

        app.UseEndpoints(endpoints => endpoints.MapControllers());

        _container.Verify();
    }

    private static void InitializeContainer(Container container)
    {
    }
}
```
and added a `TestController`:

```c#
[ApiController]
public class TestController : IDisposable
{
    // Not my real code, just for bug reporting purposes
    private readonly Stream _stream = Stream.Null;

    public void Dispose() => _stream.Dispose();
}
```

## Additional context
* SimpleInjector.Integration.AspNetCore.Mvc.Core 4.8.1
* ASP.NET Core 3.1

**Comment by dotnetjunkie** [comment]
The behavior you are seeing is by design. ASP.NET Core controllers should implement `IDisposable` or override `Dispose(bool)` from the `Controller` base class. Controllers should not hold on to disposable resources but, instead, leave that responsibility to their dependencies.

Example:

``` c#
[ApiController]
public class TestController
{
    private readonly IDependency dependency;

    public TestController(IDependency dependency) => this.dependency = dependency;
}

public sealed class DisposableImplementation : IDependency, IDisposable
{
    // Not my real code, just for bug reporting purposes
    private readonly Stream _stream = Stream.Null;

    public void Dispose() => _stream.Dispose();
}
````

**Comment by rexcfnghk** [comment]
I see, thanks @dotnetjunkie !
