### ISSUE TITLE
Verification failed for dynamic controller type

### ISSUE THREAD

**Issue by sergeyt** [simpleinjector/SimpleInjector#822]
I get error:

> System.InvalidOperationException: The configuration is invalid. Creating the instance for type FunctionController<DeleteUser, Guid, DeleteResult> failed. Unable to resolve service for type 'SheetViews.Model.Services.ICurrentUserProvider' while attempting to activate 'SheetViews.Core.AppFunctions.Users.DeleteUser'. ---> SimpleInjector.ActivationException: Unable to resolve service for type 'SheetViews.Model.Services.ICurrentUserProvider' while attempting to activate 'SheetViews.Core.AppFunctions.Users.DeleteUser'. ---> System.InvalidOperationException: Unable to resolve service for type 'SheetViews.Model.Services.ICurrentUserProvider' while attempting to activate 'SheetViews.Core.AppFunctions.Users.DeleteUser'.

```
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
  at at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
  at at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
  at at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
  at at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass19_0.<BuildScopedInstanceCreator>b__0()
  at at lambda_method(Closure )
  at at lambda_method(Closure )
  at at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
  at at SimpleInjector.InstanceProducer.GetInstance()
  --- End of inner exception stack trace ---
  at at SimpleInjector.InstanceProducer.GetInstance()
  at at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
  --- End of inner exception stack trace ---
  at at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
  at at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify, Scope verificationScope)
  at at SimpleInjector.Container.VerifyThatAllRootObjectsCanBeCreated(Scope verificationScope)
  at at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
  at at SimpleInjector.Container.Verify(VerificationOption option)
  at at SimpleInjector.Container.Verify()
  at AppStartup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
  at at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
  at at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
```
I have a `IApplicationFeatureProvider<ControllerFeature>` that generates controllers dynamically from Functions - application features.

Each dynamic controller has `TransientLifestyle`. I've tried to make `ICurrentUserProvider` to be transient, but it does not help.

For now I decided to go with LightInject, but I would like to use SimpleInjector to have this automatic verification functionality.

**Comment by dotnetjunkie** [comment]
Can you post a [mcve](https://stackoverflow.com/help/mcve)?

**Comment by sergeyt** [comment]
@dotnetjunkie actually i am not so interested 😄 atm, but maybe later

**Comment by sergeyt** [comment]
@dotnetjunkie BTW I've just used quick start and it does not work in my case, so unfortunately first experience was not smooth. I even tried to spent some time to figure out why SimpleInjector does not like dynamic controller, but without luck 😞

**Comment by dotnetjunkie** [comment]
Which version are you using?

**Comment by dotnetjunkie** [comment]
The following exception:

>  to resolve service for type 'SheetViews.Model.Services.ICurrentUserProvider' while attempting to activate 'SheetViews.Core.AppFunctions.Users.DeleteUser'.

Is thrown by the .NET Core configuration system, not by Simple Injector. You should inspectthe exception and inner exceptions closely, because the problem is not with Simple Injector, but with your ASP.NET Core configuration.

**Comment by sergeyt** [comment]
@dotnetjunkie well my configuration is pretty standard and it works with LightInject out of the box

**Comment by dotnetjunkie** [comment]
If you're not interested in providing a MVCE, there's little I can do and it's best to stick with LightInject.

**Comment by sergeyt** [comment]
@dotnetjunkie thanks for desire to help, as i said not atm. sorry for not helping to improve SI
