### ISSUE TITLE
Migration path for discovering unregistered concrete types?

### ISSUE THREAD

**Issue by Bouke** [simpleinjector/SimpleInjector#830]
In v5 the default for `ResolveUnregisteredConcreteTypes` became `false`, meaning no resolving of unregistered concrete types. While this is a sensible default, migrating to this new setting might be difficult for large codebases. There might be quite a few unregistered concrete types, which can only be discovered at runtime. This means that I have to be _very_ sure that I've covered all instances, otherwise I might cause issues in production. I could conditionally set `ResolveUnregisteredConcreteTypes = true` for production builds, but that will result in discrepancies down the road.

What would be a good solution to this?

My thinking is to run with `ResolveUnregisteredConcreteTypes = true` in production, but I would need some way of discovering unregistered concrete types. Ideally I could specify a callback somewhere and hook into that to log these concrete types. Over time all unregistered concrete types will be discovered and I can switch `ResolveUnregisteredConcreteTypes` off. I'm not aware of any such callback and would like your ideas on this.

**Comment by dotnetjunkie** [comment]
You can hook onto Simple Injector's `ResolveUnregisteredType` event to simulate `ResolveUnregisteredConcreteTypes = true` while also logging the last-minute registration of the unregistered type:

``` c#
container.ResolveUnregisteredType += (s, e) =>
{
    Type type = e.UnregisteredServiceType;
    if (!e.Handled && !type.IsAbstract)
    {
        var lifestyle = container.Options.LifestyleSelectionBehavior.SelectLifestyle(type);

        e.Register(lifestyle.CreateRegistration(type, container));
        // TODO: Log the registration of the unregistered concrete type
    }
};
```

**Comment by dotnetjunkie** [comment]
Note: I updated my previous post, to a more simplified solution.

**Comment by dotnetjunkie** [comment]
I updated the [Resolving unregistered concrete types is disallowed by default](https://simpleinjector.org/ructd) page with this guidance.

**Comment by Bouke** [comment]
This is great, thank you so much!

While testing this, I found that during `Container.Verify()` the event handler is also being called for registered collections:

```
   at Kolonel.Utilities.SimpleInjectorProvider.<>c__DisplayClass0_0.<CreateContainer>b__0(Object s, UnregisteredTypeEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at SimpleInjector.ProducerBuilders.UnregisteredTypeResolutionInstanceProducerBuilder.TryGetInstanceProducerThroughResolveUnregisteredTypeEvent(Type serviceType)
   at SimpleInjector.ProducerBuilders.UnregisteredTypeResolutionInstanceProducerBuilder.TryBuild(Type serviceType)
   at SimpleInjector.Container.BuildInstanceProducerForType(Type serviceType, Boolean autoCreateConcreteTypes)
   at SimpleInjector.Container.GetInstanceProducerForType(Type serviceType, InjectionConsumerInfo consumer, Func`1 buildInstanceProducer)
   at SimpleInjector.Internals.ContainerControlledCollection`1.GetInstanceProducerThroughUnregisteredTypeResolution(Type implementationType)
   at SimpleInjector.Internals.ContainerControlledCollection`1.GetOrCreateInstanceProducer(ContainerControlledItem item)
   at SimpleInjector.Internals.LazyEx`1.InitializeAndReturn()
   at SimpleInjector.Internals.ContainerControlledCollection`1.<>c.<.ctor>b__4_1(LazyEx`1 p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SimpleInjector.Internals.LazyEx`1.InitializeAndReturn()
   at SimpleInjector.Internals.ContainerControlledCollection`1.GetProducers()
   at SimpleInjector.Internals.ControlledCollectionHelper.ContainerControlledCollectionRegistration.GetCollectionRelationships()
   at SimpleInjector.Internals.ControlledCollectionHelper.ContainerControlledCollectionRegistration.GetRelationshipsCore()
   at SimpleInjector.InstanceProducer.GetRelationships()
   at SimpleInjector.Container.OnExpressionBuilt(InstanceProducer instanceProducer, Expression expression)
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at SimpleInjector.Internals.LazyEx`1.InitializeAndReturn()
   at SimpleInjector.InstanceProducer.BuildExpression()
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at Kolonel.Web.MvcApplication.SetupContainer()
   at Kolonel.Web.MvcApplication.Application_Start()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Web.HttpApplication.InvokeMethodWithAssert(MethodInfo method, Int32 paramCount, Object eventSource, EventArgs eventArgs)
   at System.Web.HttpApplication.ProcessSpecialRequest(HttpContext context, MethodInfo method, Int32 paramCount, Object eventSource, EventArgs eventArgs, HttpSessionState session)
   at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
```

Registered like this:
```c#
container.Collection.Register(typeof(IDomainRepository), typeof(DomainBootstrapper).Assembly);

class SomeRepository: IDomainRepository, ISomeRepository { ... }
```

Are these false positives and a side-effect of `Verify()`? When the collection is not registered, those events aren't fired. I checked a few of the concrete classes, none of them were referenced through their concrete type.

**Comment by Bouke** [comment]
> I updated the [Resolving unregistered concrete types is disallowed by default](https://simpleinjector.org/ructd) page with this guidance.

That's great, and I think it will be very helpful for others doing the migration. FYI, your link references the master branch, whereas you committed this change to the [v5 branch](https://github.com/simpleinjector/Documentation/commit/6e27ea0a66890de6e4edd64e89baaa498dce27c4).

**Comment by dotnetjunkie** [comment]
These are certainly false positives, but not so much a side effect of `Verify()`, but rather a property of how collections are built. When building an item of a registered collection, Simple Injector:

* first checks to see if that item (implementation type, `SomeRepository` in your case) has an explicit registration. If so it uses that registration for the collection
* if not, it falls back to calling the `ResolveUnregisteredType` event.
* if `ResolveUnregisteredType` didn't cause the implementation type to get registered, Simple Injector creates an InstanceProducer for that implementation type itself.

So the (unfortunate) step in the workflow is the triggering of the `ResolveUnregisteredType` event. This causes false positives for collection items, and this might actually be tricky to work around, which is unfortunate.

That might make the updated migration advise in the documentation not as usable as it should.

**Comment by Bouke** [comment]
I think I'll add `&& !container.IsVerifying` to determine whether to log. Those events will either turn out to be false positives, or be caught when verifying the container anyway. So ignoring them in my logging will not be an issue and allow me to focus on the true positives.

**Comment by dotnetjunkie** [comment]
> I think I'll add && !container.IsVerifying to determine whether to log

That won't work. `ResolveUnregisteredType` is triggered just once per type, so if you wrap your `ResolveUnregisteredType` code in an `if (!container.IsVerifying)` block, while still calling `container.Verify()`, you won't get any items in your log, even if you still have concrete unregistered types.

Perhaps there's a way for you to filter out types that are part of a collection.
