### ISSUE TITLE
Using DependencyMetadata<T> inside a decorator applied to each individual type in a registered collection of types throws an exception during container verification

### ISSUE THREAD

**Issue by RyanMarcotte** [simpleinjector/SimpleInjector#878]
## To Reproduce

``` csharp
public class DecoratorWithDependencyMetadataAppliedToCollectionTests
{
    [Fact]
    public void SuccessfullyAppliesDecoratorWithDependencyMetadataToEachTypeInServiceCollection()
    {
        var container = new Container();
        container.Collection.Register<IDoTheThing>(new [] { typeof(Thing1), typeof(Thing2) });
        container.RegisterDecorator<IDoTheThing, Decorator>();

        container.Verify(); // throws exception
    }

    private interface IDoTheThing
    {
        void DoTheThing();
    }

    private class Thing1 : IDoTheThing
    {
        public void DoTheThing() { }
    }

    private class Thing2 : IDoTheThing
    {
        public void DoTheThing() { }
    }

    private class Decorator : IDoTheThing
    {
        private readonly IDoTheThing _thing;
        private readonly DependencyMetadata<IDoTheThing> _dependencyMetadata;

        public Decorator(IDoTheThing thing, DependencyMetadata<IDoTheThing> dependencyMetadata)
        {
            _thing = thing;
            _dependencyMetadata = dependencyMetadata;
        }

        public void DoTheThing() => _thing.DoTheThing();
    }
}
```

The above code is the minimum needed to reproduce the problem.  In my own code, I have two decorators applied instead of just one.  That is why I would like to use `DependencyMetadata<T>`: to retrieve information about the decorated implementation type (either `Thing1` or `Thing2` in the example above) for logging purposes.

## Expected behavior
Per my understanding of the documentation [here](https://simpleinjector.readthedocs.io/en/latest/advanced.html#accessing-a-dependency-s-metadata) and [here](https://simpleinjector.readthedocs.io/en/latest/aop.html#applying-lifestyles-to-decorators)...
- the collection of implementations for service type `T` is registered
- a decorator is applied to individual implementation types in that collection of service type `T`
- the decorator has access to the implementation type being decorated by using `DependencyMetadata<T>`

## Actual behavior

> System.InvalidOperationException: The configuration is invalid. Creating the instance for type DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing 
failed. No registration for type DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing 
could be found. There is, however, a registration for IEnumerable&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>; 
Did you mean to call GetAllInstances&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>() 
or depend on IEnumerable&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>? Please see 
https://simpleinjector.org/collections for more information about registering and resolving collections.

```
at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
at SimpleInjector.Container.Verify(VerificationOption option)
at SimpleInjector.Container.Verify()
at (testClass).(methodName) in (file):line 123
```

> SimpleInjector.ActivationException: No registration for type DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing could be found. There is, 
however, a registration for IEnumerable&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>; Did you 
mean to call GetAllInstances&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>() or depend on 
IEnumerable&lt;DecoratorWithDependencyMetadataAppliedToCollectionTests.IDoTheThing>? 
Please see https://simpleinjector.org/collections for more information about registering and resolving collections.

```
at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type type)
at SimpleInjector.ProducerBuilders.DependencyMetadataInstanceProducerBuilder.BuildInstanceProducerForDependencyMetadata(Type metadataType)
at SimpleInjector.ProducerBuilders.DependencyMetadataInstanceProducerBuilder.TryBuild(Type serviceType)
at SimpleInjector.Container.BuildInstanceProducerForType(Type serviceType, Boolean autoCreateConcreteTypes)
at SimpleInjector.Container.<>c__DisplayClass192_0.<GetRegistrationEvenIfInvalid>g__BuildProducer|0()
at SimpleInjector.Container.GetInstanceProducerForType(Type serviceType, InjectionConsumerInfo consumer, Func`1 buildInstanceProducer)
at SimpleInjector.Container.GetRegistrationEvenIfInvalid(Type serviceType, InjectionConsumerInfo consumer, Boolean autoCreateConcreteTypes)
at SimpleInjector.Advanced.DefaultDependencyInjectionBehavior.GetInstanceProducer(InjectionConsumerInfo dependency, Boolean throwOnFailure)
at SimpleInjector.ContainerOptions.GetInstanceProducerFor(InjectionConsumerInfo consumer)
at SimpleInjector.Registration.BuildConstructorParameters(ConstructorInfo constructor)
at SimpleInjector.Registration.BuildNewExpression()
at SimpleInjector.Registration.BuildTransientExpression()
at SimpleInjector.Lifestyles.TransientLifestyle.TransientRegistration.BuildExpression()
at SimpleInjector.Decorators.ServiceDecoratorExpressionInterceptor.ReplaceOriginalExpression(Registration decoratorRegistration)
at SimpleInjector.Decorators.ServiceDecoratorExpressionInterceptor.ApplyDecorator(Type closedDecoratorType)
at SimpleInjector.Decorators.DecoratorInterceptor.TryToApplyDecorator(ExpressionBuiltEventArgs e)
at SimpleInjector.Decorators.DecoratorInterceptor.ExpressionBuilt(Object sender, ExpressionBuiltEventArgs e)
at SimpleInjector.Container.OnExpressionBuilt(InstanceProducer instanceProducer, Expression expression)
at SimpleInjector.InstanceProducer.BuildExpressionInternal()
at SimpleInjector.Internals.LazyEx`1.InitializeAndReturn()
at SimpleInjector.InstanceProducer.BuildExpression()
at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
```

**Comment by dotnetjunkie** [comment]
Thank you for this detailed report. Unfortunately, injecting `DependencyMetadata<T>` is not supported in decorators. For this another mechanism currently exists, which is `DecoratorContext` as explained [here](https://simpleinjector.org/aop+using-contextual-information-inside-decorators).

For consistency, however, it might be good to add `DependencyMetadata<T>` support for decorators as well.

**Comment by dotnetjunkie** [comment]
Moved to new feature request #879.

**Comment by RyanMarcotte** [comment]
I somehow missed that section of the documentation.  Thank you for pointing me in the right direction!
