### ISSUE TITLE
Failing to CrossWire to ServiceCollection and resolve instance of ILogger 

### ISSUE THREAD

**Issue by KeyboardMonkey221** [simpleinjector/SimpleInjector#896]
So, I need to dependency inject a logger (specifically one implemented by NLog) throughout my application. The application is set up to depend on SimpleInjector to resolve all injections.

NLog provides a function, `.UseNLog()` that can be applied to the WebHostBuilder which is successfully registering an NLog instance in the .NET ServiceCollection. I want the SimpleInjector container to resolve all `.GetInstance<ILogger>()` to that registration in the .NET ServiceCollection.

Within `ConfigureServices(IServiceCollection services)`, I've executed the following code:
``` C#
services.AddSimpleInjector(container, si => {
     si.CrossWire<ILogger>();
}
```
Where container is of type Container.

When I attempt to run the application, it fails at the first delegate given to a `.Register(...)` method that attempts to execute the following:
``` C#
container.GetInstance<ILogger>()
```
Which is the same instance of the SimpleInjector declared above.

The exception is as follows:
``` 
No service for type 'Microsoft.Extensions.Logging.ILogger' has been registered. ---> SimpleInjector.ActivationException: The registered delegate for type OurClassName threw an exception. The registered delegate for type ILogger threw
 an exception. ---> System.InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILogger' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass23_0.<BuildScopedInstanceCreator>b__0()
   at lambda_method(Closure )
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceFromProducer(InstanceProducer instanceProducer, Type serviceType)
   at SimpleInjector.Container.GetInstanceForRootType[TService]()
   at SimpleInjector.Container.GetInstance[TService]()
   at SimpleInjectorRegistration.AWS.HandlerTracer.<>c__DisplayClass0_0.<Register>b__0() in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\Shared\RateSetter.SimpleInjector\SimpleInjectorRegistration.AWS\HandlerTracer.cs:line 1
6
   at lambda_method(Closure )
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstance(Func`1 instanceCreator)
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstanceWithNullCheck()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.GetInterceptedInstance()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.BuildExpression()
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at SimpleInjector.Internals.LazyEx`1.get_Value()
   at SimpleInjector.InstanceProducer.BuildExpression()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.BuildExpression()
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at CreditEngineService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:l
ine 161
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Application is shutting down...
```

Any help would be much appreciated!

**Comment by KeyboardMonkey221** [comment]
To try and hack my way around, I've attempted to copy the `ServiceCollection`, build an instance of the `ServiceProvider`, and provide the container a delegate to register `ILogger` from that. This can be seen in the following: 

This is all within `ConfigureServices(...)`

``` C#
var serviceProviderFactory = new DefaultServiceProviderFactory();
var extraServiceCollection = serviceProviderFactory.CreateBuilder(services);
var serviceProvider = extraServiceCollection.BuildServiceProvider();
container.Register<ILogger>(() => serviceProvider.GetService<ILogger>());
```

I kept the crosswiring option on above, and now I'm receiving the following exception:

``` C#
Application startup exception: System.AggregateException: One or more errors occurred. (Type ILogger has already been registered. If your intention is to resolve a collection of ILogger implementations, use the Container.Collection.Register overloads. For
 more information, see https://simpleinjector.org/coll1. If your intention is to replace the existing registration with this new registration, you can allow overriding the current registration by setting Container.Options.AllowOverridingRegistrations to t
rue. For more information, see https://simpleinjector.org/ovrrd.) ---> System.InvalidOperationException: Type ILogger has already been registered. If your intention is to resolve a collection of ILogger implementations, use the Container.Collection.Regist
er overloads. For more information, see https://simpleinjector.org/coll1. If your intention is to replace the existing registration with this new registration, you can allow overriding the current registration by setting Container.Options.AllowOverridingR
egistrations to true. For more information, see https://simpleinjector.org/ovrrd.
   at SimpleInjector.Internals.NonGenericRegistrationEntry.ThrowWhenTypeAlreadyRegistered(InstanceProducer producer)
   at SimpleInjector.Internals.NonGenericRegistrationEntry.Add(InstanceProducer producer)
   at SimpleInjector.Container.AddInstanceProducer(InstanceProducer producer)
   at SimpleInjector.Container.AddRegistrationInternal(Type serviceType, Registration registration)
   at SimpleInjector.Container.AddRegistration(Type serviceType, Registration registration)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass7_0.<CrossWire>b__0(Object s, ContainerLockingEventArgs e)
   at SimpleInjector.ContainerOptions.RaiseContainerLockingAndReset()
   at SimpleInjector.Container.NotifyAndLock()
   at SimpleInjector.Container.LockContainer()
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at SimpleInjector.Util.SimpleInjectorWrapper.Resolve[T]() in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\Shared\RateSetter.SimpleInjector\SimpleInjector.Util\SimpleInjectorWrapper.cs:line 31
   at CreditEngineService.ServiceMessageBusManager.Subscribe(IContainer container, String messageBusNamespace) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\ServiceMessageBusManager.
cs:line 24
   at CreditEngineService.Startup.serviceMessageBusSetup(IContainer simpleInjectorWrapper) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:line 180
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CreditEngineService.Startup.useWebSockets(IApplicationBuilder app, IContainer simpleInjectorWrapper) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:line 174
   at CreditEngineService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:l
ine 154
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.InvalidOperationException: Type ILogger has already been registered. If your intention is to resolve a collection of ILogger implementations, use the Container.Collection.Register overloads. For more information, see https
://simpleinjector.org/coll1. If your intention is to replace the existing registration with this new registration, you can allow overriding the current registration by setting Container.Options.AllowOverridingRegistrations to true. For more information, s
ee https://simpleinjector.org/ovrrd.
   at SimpleInjector.Internals.NonGenericRegistrationEntry.ThrowWhenTypeAlreadyRegistered(InstanceProducer producer)
   at SimpleInjector.Internals.NonGenericRegistrationEntry.Add(InstanceProducer producer)
   at SimpleInjector.Container.AddInstanceProducer(InstanceProducer producer)
   at SimpleInjector.Container.AddRegistrationInternal(Type serviceType, Registration registration)
   at SimpleInjector.Container.AddRegistration(Type serviceType, Registration registration)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass7_0.<CrossWire>b__0(Object s, ContainerLockingEventArgs e)
   at SimpleInjector.ContainerOptions.RaiseContainerLockingAndReset()
   at SimpleInjector.Container.NotifyAndLock()
   at SimpleInjector.Container.LockContainer()
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at SimpleInjector.Util.SimpleInjectorWrapper.Resolve[T]() in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\Shared\RateSetter.SimpleInjector\SimpleInjector.Util\SimpleInjectorWrapper.cs:line 31
   at CreditEngineService.ServiceMessageBusManager.Subscribe(IContainer container, String messageBusNamespace) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\ServiceMessageBusManager.
cs:line 24
   at CreditEngineService.Startup.serviceMessageBusSetup(IContainer simpleInjectorWrapper) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:line 180<---

Application is shutting down...
```

Removing the `.CrossWire()` option yields a different result:
``` C#
Application startup exception: System.InvalidOperationException: The configuration is invalid. Creating the instance for type HandlerTracer failed. The registered delegate for type HandlerTracer threw an exception. The registered delegate for type ILogger
 threw an exception. The registered delegate for type ILogger returned null. ---> SimpleInjector.ActivationException: The registered delegate for type HandlerTracer threw an exception. The registered delegate for type ILogger threw an exception. The regis
tered delegate for type ILogger returned null. ---> SimpleInjector.ActivationException: The registered delegate for type ILogger threw an exception. The registered delegate for type ILogger returned null. ---> SimpleInjector.ActivationException: The regis
tered delegate for type ILogger returned null.
   at SimpleInjector.Registration.ThrowWhenNull[TService](TService instance)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceFromProducer(InstanceProducer instanceProducer, Type serviceType)
   at SimpleInjector.Container.GetInstanceForRootType[TService]()
   at SimpleInjector.Container.GetInstance[TService]()
   at SimpleInjectorRegistration.AWS.HandlerTracer.<>c__DisplayClass0_0.<Register>b__0() in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\Shared\RateSetter.SimpleInjector\SimpleInjectorRegistration.AWS\HandlerTracer.cs:line 1
6
   at lambda_method(Closure )
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstance(Func`1 instanceCreator)
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.CreateInstanceWithNullCheck()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.GetInterceptedInstance()
   at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonLifestyleRegistration`1.BuildExpression()
   at SimpleInjector.InstanceProducer.BuildExpressionInternal()
   at SimpleInjector.Internals.LazyEx`1.get_Value()
   at SimpleInjector.InstanceProducer.BuildExpression()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.BuildExpression()
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at CreditEngineService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\lance.young\Plenti\source\AllServices\Services\CreditEngineService\CreditEngineService\CreditEngineService\Startup.cs:l
ine 165
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Application is shutting down...
```

Is something fishy going on here?

**Comment by KeyboardMonkey221** [comment]
I've resolved the issue with a simple fix:

``` C#
services.AddSimpleInjector(container, si =>
{
      si.AddLogging();
});
```

Though why didn't the solution above work?

**Comment by dotnetjunkie** [comment]
You were trying to cross-wire a dependency, ILogger, that hasn't been registered in MS.DI. It only knows about its generic counterpart. In .NET Core you can only inject `ILogger<>` due to limitations of MS.DI. Ghat is, unless you use Simple Injector with its contextual injection capabilites. But in that case you will habe to instruct  Simple Injector to make a mapping from ILogger to `ILlgger<>`. This can be done by hand, or by calling .AddLogging.

**Comment by dotnetjunkie** [comment]
For more info, see https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html#integrating-with-microsoft-logging

**Comment by KeyboardMonkey221** [comment]
Thank you for clarifying that - it's much appreciated.
