### ISSUE TITLE
Hybrid Async Scoped MVC 5 + Async Method bug

### ISSUE THREAD

**Issue by leonardolb** [simpleinjector/SimpleInjector#983]
Hi!
i'm facing this error and I really can't go through it.

<img width="1710" alt="image" src="https://github.com/simpleinjector/SimpleInjector/assets/109328159/e7aa4967-8738-48fc-8c8c-294ab52358ea">

My code: 

it start at this action:

<img width="771" alt="image" src="https://github.com/simpleinjector/SimpleInjector/assets/109328159/386dbbdd-0445-4aad-8420-57f3e211f329">

goes to this block
<img width="909" alt="image" src="https://github.com/simpleinjector/SimpleInjector/assets/109328159/fd23e241-8fd4-4612-ab86-4564e32c6ac9">

and  exception is thrown at the highlighted part of code.

Can anyone help me?

this is my lifestyle 
<img width="963" alt="image" src="https://github.com/simpleinjector/SimpleInjector/assets/109328159/bfdba418-2ccd-4ece-a0a5-fb5f9cf9aad4">

It's an ASP.NET MVC5 app that runs some background tasks, WebAPI controllers and SignalR.

thanks!!

**Comment by dotnetjunkie** [comment]
Hi @leonardolb,

I've got trouble reading the images on my mobile phone. Would you mind replacing them with actual text, as was requested in the [bug report template](https://github.com/simpleinjector/SimpleInjector/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) you used while filling in your question?

Thanks in advance

**Comment by dotnetjunkie** [comment]
And don't forget to post a full stack trace

**Comment by leonardolb** [comment]
Sorry about that!!

Im facing this exception:

`PersonDataConfigBO is registered using the 'Hybrid Async Scoped / Web Request' lifestyle, but the instance is requested outside the context of an active (Hybrid Async Scoped / Web Request) scope. Please see https://simpleinjector.org/scoped for more information about how apply lifestyles and manage scopes.`


My stacktrace is
`SimpleInjector.ActivationException: PersonDataConfigBO is registered using the 'Hybrid Async Scoped / Web Request' lifestyle, but the instance is requested outside the context of an active (Hybrid Async Scoped / Web Request) scope. Please see https://simpleinjector.org/scoped for more information about how apply lifestyles and manage scopes.
   at SimpleInjector.Scope.GetScopelessInstance(ScopedRegistration registration)
   at SimpleInjector.Scope.GetInstance[TImplementation](ScopedRegistration registration, Scope scope)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance[TService]()
   at AdSolutions.AdData.Context.Pessoa.PessoaContext.<ConsultarCNPJ>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at AdSolutions.Site.AdData.Controllers.PersonController.<Detail>d__3.MoveNext() in C:\Users\leonardo\Desktop\svn\AdTraffic\master\AdSolutions.Site.Host\Areas\AdData\Controllers\PersonController.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)`


Everything start at my PersonController "Detail" Action. It async calls "ConsultarCNPJ" in my context class

```
public async Task<JsonResult> Detail(PessoaModel model, PessoaDadoPessoaConfigModel documento)
        {
            if (model == null)
                model = new PessoaModel();

            var service = base.CreateContext<IPessoaContext>();

            if (documento != null)
            {
                var consultarCnpj = false;

                if (consultarCnpj.False())
                    model = service.ObterNovo(documento);
                else
                    **_model = await service.ConsultarCNPJ(documento);_**
            }
            else if (model.State.In(ModelStateType.Normal))
                model = service.ObterDetalhes(model);

            return AjaxViewResult(new PessoaViewModel(model));
        }
```
 "ConsultarCNPJ"  is a simple method that triggers a mediator (ThirdPartyCommandMediator) and awaits all available commands complete (just one expected for this ConsultarCNPJThirdPartyCommand).

When finished, base.CreateBO<IPersonDataConfigBO>().List is called to continue some procedures. 

base.CreateBO<IPersonDataConfigBO>().List is not async and it goes to directly to database (oracle).

**CreateBO** method is just a wrapper to simpleinjector Container.Resolve.

```
public async Task<PessoaModel> ConsultarCNPJ(PessoaDadoPessoaConfigModel documento)
        {
            var command = new ConsultarCNPJThirdPartyCommand
            {
                CNPJ = documento.dsValor.RemoveSpecialCharacters().RemoveDiacritics()
            };

            var results = await **ThirdPartyCommandMediator**.Handle(command).ConfigureAwait(false);

            var queryData = results[0];

            if (queryData.Success)
            {
                var pessoa = queryData.Command.ReturnValue.Pessoa;

                var documentosPessoa = **base.CreateBO<IPersonDataConfigBO>().List**(
                    new PaisModel { sqPais = PaisModel.Brasil },
                    TipoPessoa.Juridica,
                    Situacao.Ativo).Select(sel => new PessoaDadoPessoaConfigModel
                    {
                        DadoPessoaConfig = sel,
                        State = ModelStateType.New
                    }).ToList();
}
```


I'm using  "Lifestyle = Lifestyle.CreateHybrid(new SimpleInjector.Lifestyles.AsyncScopedLifestyle(), new WebRequestLifestyle())" as my lifestyle.

Finally, this is the Handler triggered when **ThirdPartyCommandMediator**.Handle() is invoked


```
public override async Task<ThirdPartyCommandHandlerContext<ConsultarCNPJThirdPartyCommand>> Handle(ThirdPartyCommandHandlerContext<ConsultarCNPJThirdPartyCommand> commandContext)
        {

            var targetApp = new SERPROPartyApp(commandContext.Context);
            var command = commandContext.Command;

            if (targetApp.BaseUrl.IsNullOrWhiteSpace())
                return commandContext;
            else
            {
                var client = new SERPRORestClient(targetApp.Username, targetApp.Password, targetApp.BaseUrl);

                var dados = await client.Consultar(command.CNPJ).ConfigureAwait(false);
}


public async Task<CNPJ> Consultar(string cnpj)
        {
            var request = new RestRequest("/consulta-cnpj-df/v2/basica/" + cnpj, Method.Get);

            var response = await this._client.ExecuteAsync<CNPJ>(request).ConfigureAwait(false);

            return response?.Data;
        }
```

**Comment by dotnetjunkie** [comment]
Can you debug through your application and determine exactly after which line of code the scope is gone?

**Comment by leonardolb** [comment]
Yes!
Exceptions is thrown at this line when resoling IPersonDataConfigBO 

var documentosPessoa = base.CreateBO<IPersonDataConfigBO>().List in ConsultarCNPJ method.

**Comment by dotnetjunkie** [comment]
Sorry, that's not what I meant. It's clear to me where the exception is thrown, but there is a point in the application that Simple Injector's `Scope` is gone. This is what eventually leads to the exception. What I want to know is: what is the first ocurrance in your code where that `Scope` is gone. This will likely be long before the exception happens.

In order to test this, you might need to make some temporary adjustments to your code; the easiest way to test is by calling into the container to resolve a scoped dependency, for instance just after the lines of code I mentioned above.

**Comment by leonardolb** [comment]
Sorry my misunderstanding!

I've debuged my code, scope is gone after 

`var response = await this._client.ExecuteAsync<CNPJ>(request).ConfigureAwait(false);`

**Comment by leonardolb** [comment]
Unfortunately I can't debug further into ExecuteAsync as its is a method from RestSharp.RestClient class.

**Comment by leonardolb** [comment]
Thanks!
I've removed .ConfigureAwait(false) from it just to test and scope stopped being lost. However, I don't feel I should do it as it may cause deadlock at some background tasks that consumes this same method.

I'll step away from lazyloading so!

thanks!

**Comment by dotnetjunkie** [comment]
> I've removed .ConfigureAwait(false)

I didn't expect this.

> However, I don't feel I should do it as it may cause deadlock at some background tasks that consumes this same method.

You don't have to worry about that. This only holds when building client applications such as WPF and Win Forms. This doesn't hold for ASP.NET. AFAIK, It will never deadlock on this.

**Comment by leonardolb** [comment]
Maybe i need to remove other ConfigureAwait I have so, maybe they are causing some trouble too i guess
