### ISSUE TITLE
Owin WebAPI support is broken without ResolveUnregisteredCollections = true in 3.0.1

### ISSUE THREAD

**Issue by Tornhoof** [simpleinjector/SimpleInjector#99]
Hi,
due to the changes in Issue #98  pretty much every OWIN WebAPI app is now broken with the following exception:

SimpleInjector.ActivationException was unhandled by user code
  HResult=-2146233088
  Message=No registration for type IEnumerable<IExceptionLogger> could be found.
  Source=SimpleInjector
  StackTrace:
       at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
       at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
       at SimpleInjector.Container.GetInstance(Type serviceType)
       at SimpleInjector.Container.GetAllInstances(Type serviceType)
       at SimpleInjector.Integration.WebApi.SimpleInjectorWebApiDependencyResolver.System.Web.Http.Dependencies.IDependencyScope.GetServices(Type serviceType)
       at System.Web.Http.Services.DefaultServices.GetServices(Type serviceType)
       at System.Web.Http.ServicesExtensions.GetServices[TService](ServicesContainer services)
       at System.Web.Http.Controllers.ServicesContainer.CreateExceptionServicesLogger()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at System.Web.Http.ExceptionHandling.ExceptionServices.GetLogger(ServicesContainer services)
       at Owin.WebApiAppBuilderExtensions.CreateOptions(IAppBuilder builder, HttpServer server, HttpConfiguration configuration)
       at Owin.WebApiAppBuilderExtensions.UseWebApi(IAppBuilder builder, HttpConfiguration configuration)
       at Example.Test.Startup.ConfigureLifetime(IAppBuilder app, Engine engine) in C:\Example\Backend\API\Test\App_Start\Startup.cs:line 49
       at Example.Test.Startup.ConfigureEngine(IAppBuilder app, IDictionary`2 settings) in C:\Example\Backend\API\Test\App_Start\Startup.cs:line 25
       at Example.Test.Startup.Configuration(IAppBuilder app, IDictionary`2 settings) in C:\Example\Backend\API\Test\Startup.cs:line 20
       at Example.Test.Startup.Configuration(IAppBuilder app) in C:\Example\Backend\API\Test\Startup.cs:line 15
  InnerException: 

It happens in the app.UseWebApi() call:
```
            // Create and assign a dependency resolver for Web API to use
            var config = new HttpConfiguration {DependencyResolver = engine.CreateWebApiDependencyResolver()};
            WebApiConfig.Register(config, engine);
            FilterConfig.RegisterGlobalApiFilters(config.Filters, engine.GetAllInstancesFunctor());
            app.UseWebApi(config); <-- here
            config.EnsureInitialized();
```

The workaround is ResolveUnregisteredCollections = true (to get the old behaviour).
While I understand the reasoning in Issue #98, this should not happen.

I can provide a project to reproduce the problem if necessary.

**Comment by filipw** [comment]
yeah, I just ran into the exact same problem

```
   at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
   at SimpleInjector.Container.GetInstanceFromProducer(InstanceProducer instanceProducer, Type serviceType)
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at SimpleInjector.Container.GetAllInstances(Type serviceType)
   at SimpleInjector.Integration.WebApi.SimpleInjectorWebApiDependencyResolver.System.Web.Http.Dependencies.IDependencyScope.GetServices(Type serviceType)
   at System.Web.Http.Services.DefaultServices.GetServices(Type serviceType)
   at System.Web.Http.ServicesExtensions.GetServices[TService](ServicesContainer services)
   at System.Web.Http.ServicesExtensions.GetExceptionLoggers(ServicesContainer services)
   at System.Web.Http.ExceptionHandling.ExceptionServices.CreateLogger(ServicesContainer services)
   at System.Web.Http.Controllers.ServicesContainer.CreateExceptionServicesLogger()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at System.Web.Http.ExceptionHandling.ExceptionServices.GetLogger(ServicesContainer services)
   at Owin.WebApiAppBuilderExtensions.CreateOptions(IAppBuilder builder, HttpServer server, HttpConfiguration configuration)
   at Owin.WebApiAppBuilderExtensions.UseWebApi(IAppBuilder builder, HttpConfiguration configuration)
   at Foo.Startup.Configuration(IAppBuilder app) in c:\Users\filip\Documents\dev\Foo\Startup.cs:line 57
```

**Comment by dotnetjunkie** [comment]
You can fallback to the old behavior by calling:

``` c#
container.Options.ResolveUnregisteredCollections = true;
```

We will investigate and push a patch release to NuGet a.s.a.p.

**Comment by filipw** [comment]
Yep that's what I did already, and indeed it fixes the problem.
thanks

**Comment by dotnetjunkie** [comment]
Version 3.0.2. of both the Web API and MVC integration packages are pushed to NuGet. They solve this issue.

**Comment by filipw** [comment]
awesome :+1:
